### Pipeline options

# Input parameters
input_format: "pod5" #pod5 or bam (aligned bam)
basecalling_mode: "methylation" #methylation or basic
variant_calling_mode: "somatic" #germline or somatic

# Output parameter
output_dir: "path/to/data_output/"

# Select which parts of the pipeline should be run
steps:
  basecalling: true
  alignment: true
  differential_methylation_sample: true
  differential_methylation_condition: true
  snv_calling: true
  sv_calling: true
  phasing: true
  cnv_calling: true

# Path to design file
design: "path/to/my_design.tsv"

# References information
references:
  genome: "/mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.109/homo_sapiens.GRCh38.109.fasta"
  genome_fai: "/mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.109/homo_sapiens.GRCh38.109.fasta.fai"
  genome_snpEff: "GRCh38.99" #GRCh38.109 doesn't exist in snpEff database
  dbnsfp: "/mnt/beegfs/database/bioinfo/Index_DB/dbNSFP/4.1/GRCh38/dbNSFP4.1a.txt.gz"
  clinvar: "/mnt/beegfs/database/bioinfo/Index_DB/ClinVar/GRCh38/clinvar_20230710.vcf.gz"
  genome_annotsv: "GRCh38"
  annotsv: "/mnt/beegfs/database/bioinfo/bigr_long-reads_bulk/ANNOTATIONS/AnnotSV_annotations/"
  code_symbol_conversion: "/mnt/beegfs/database/bioinfo/bigr_long-reads_bulk/REFERENCES/DMR/GRCh38/correspondance_table_ENST_ENSG.tsv"
  fastq_screen_conf: "/mnt/beegfs/database/bioinfo/Index_DB/Fastq_Screen/0.15.3/minimap2/fastq_screen.conf"
  chromosomes: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'MT', 'X', 'Y']

# DMR references
Alu: "/mnt/beegfs/database/bioinfo/bigr_long-reads_bulk/REFERENCES/DMR/GRCh38/Alu_ucsc_grch38.txt"
CpG: "/mnt/beegfs/database/bioinfo/bigr_long-reads_bulk/REFERENCES/DMR/GRCh38/CpG_ucsc_grch38.txt"
Transcript: "/mnt/beegfs/database/bioinfo/bigr_long-reads_bulk/REFERENCES/DMR/GRCh38/Transcript_ucsc_grch38.txt"

# Basecalling parameters
dorado_basecaller:
  model: "/mnt/beegfs/pipelines/dorado/model/model_r10/dna_r10.4.1_e8.2_400bps_sup@v4.2.0"
  model_meth: "/mnt/beegfs/pipelines/dorado/model/model_r10/dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mCG_5hmCG@v2"
  meth_type: ["5mCG","5hmCG"] #mandatory if basecalling is set to false.

# Germline SNV calling parameters
clair3:
  model: ["/mnt/beegfs/database/bioinfo/bigr_long-reads_bulk/MODELS/rerio/clair3_models/r1041_e82_400bps_sup_v430"] # R10 model from Rerio for Dorado SUP

# Somatic SNV parameters
clairs:
  model: "ont_r10_dorado_sup_5khz" # R10 model 

# SNV annotation parameters
snpsift:
  filters: ["(FILTER = 'PASS')", "( QUAL >= 10 )", "( QUAL >= 15 )"] # will output 3 files (1 by filter)

# SNV graph parameters
maftools:
  genes_of_interest: "path/to/my_genes_list.txt"

# CNV parameters
spectre:
  blacklist: "/mnt/beegfs/database/bioinfo/bigr_long-reads_bulk/REFERENCES/Spectre/blacklists/grch38_renamed_blacklist_spectre.bed"
