intro_text: "This report summarises the quality control of the analysis by the BiGR Long-Reads Bulk DNA pipeline."
report_header_info:
    - Contact E-mail: "bigr@gustaveroussy.fr"
    - Application Type: "Nanopore Long reads DNA-seq"
    - Sequencing Platform: "PromethION 48"

module_order:
    - fastqc
    - fastq_screen
    - nanostat
    - qualimap
    - mosdepth
    - custom_content:
        name: "Methylation QC"
        path_filters:
            - "*barplot_methylated_CG_*_mqc.png"
            - "*per_pos_per_strand_gam_ratio_*_chr*_*_mqc.png"
  
custom_logo: "/mnt/beegfs/pipelines/bigr_long-reads_bulk/2.0.0/images/bigr_ContourBlanc_96dpi_100x100.png"
custom_logo_title: "Bioinformatics Core Facility - Gustave Roussy"

fn_clean_exts:
    - "_wgs_mode"
    - "_sorted"
    - ".fastq.gz"
    - "_screen.txt"
  
software_versions:
    nanostat: "1.42.0"
    qualimap: "2.3"
    mosdepth: "0.3.4"
    pipeline: "2.0.0"
