intro_text: "This report summarises the quality control of the analysis by the BiGR Long-Reads Bulk DNA pipeline."
report_header_info:
    - Contact E-mail: "bigr@gustaveroussy.fr"
    - Application Type: "Nanopore Long reads DNA-seq"
    - Sequencing Platform: "PromethION 48"

module_order:
    - fastqc
    - fastq_screen
    - nanostat
    - qualimap
    - mosdepth
    - samtools
    - custom_content

#custom_data:
#    Methylation_QC:
#        #id: "Methylation_QC"
#        section_name: "Methylation QC"
#    Methylation_QC2:
#        #id: "Methylation_QC2"
#        section_name: "Methylation QC 2"
#sp:
#    Methylation_QC:
#        fn: "*barplot_methylated_CG_*_mqc.png"
#    Methylation_QC2:
#        fn: "*per_pos_per_strand_gam_ratio_*_chr*_*_mqc.png"
#custom_content:
#    order:
#        - Methylation_QC
#        - Methylation_QC2

#ignore_images: false

custom_logo: "/mnt/beegfs/pipelines/bigr_long-reads_bulk/2.0.0/images/bigr_ContourBlanc_96dpi_100x100.png"
custom_logo_title: "Bioinformatics Core Facility - Gustave Roussy"

fn_clean_exts:
    - "_wgs_mode"
    - "_sorted"
    - ".fastq.gz"
    - "_screen.txt"
    - "_mqc.png"
    - "_stats"
    - "_flagstat"
    - "_idxstats"
    - "_coverage"
    - "_NanoStats"

software_versions:
    Nanostat: "1.42.0"
    Qualimap: "2.3"
    Mosdepth: "0.3.4"
    Samtools: "1.11"
    pipeline: "2.0.0"
