restart-times: 1
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 1
jobs: 60
keep-going: true
reason: false
printshellcmds: true
jobname: "{name}.{jobid}.snakejob"
use-conda: true
conda-prefix: /mnt/beegfs/pipelines/bigr_long-reads_bulk/dev_test/envs/compiled_conda
